#### açıklama

Bu örnekteki ana fikri anlamak biraz zor olabilir. <br>

Elimizde bir sınıf hiyerarşisi içinde bulunan bir _exception_ sınıfı türünden bir hata nesnesi var.<br>
Dİkkat: Burada söz konusu hata sınıfı hiyerarşisi içinde aynı taban sınıftan kalıtm yoluyla elde edilmiş çok sayıda özelleştirilmiş _exception_ sınıfı olabilir.<br>
Bu hata nesnesini bir fonksiyona göndermek ve çağırdığımız bu fonksiyonun _exception_ nesnesinin dinamik türünü koruyarak gönderdiğimiz hata nesnesini _throw_ etmesini (göndermesini) istiyoruz.

<!--

-->
